language: python
python:
    - "2.7"
    - "pypy"
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements.txt
script:
    - python -m json.tool < cookiecutter.json
    - py.test
    - flake8 tests
