language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
install:
    - pip install -r requirements.txt
script:
    - py.test
    - flake8 setup.py {{cookiecutter.repo_name}} tests
after_success:
  - coveralls
