language: python
python:
    - "2.7"
    - "pypy"
    - "3.5"
install:
    - pip install --upgrade -r requirements.txt
script:
    - py.test
    - flake8 setup.py {{cookiecutter.repo_name}} tests
after_success:
    - codecov
